server:
  port: 8081
eureka:
  client:
  #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    service-url:
       defaultZone: http://peer1:${server.port}/eureka/
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: eureka-server
#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#      health:
#        show-details: ALWAYS
 #显示ip注册
 #eureka.instance.preferIpAddress=true
 #eureka.instance.prefer-ip-address=true
 #eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}