#主配置文件，配置了这个会优先读取里面的属性覆盖主配置文件的属性
#spring.profiles.active=peer1

#server.port=8080
##由于该应用为注册中心，所以设置为false, 代表不向注册中心注册自己
#eureka.client.register-with-eureka=false
##由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为false
#eureka.client.fetch-registry=false
##指定服务注册中心的地址
#eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/

server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://peer1:${server.port}/eureka/
  instance:
    hostname: peer1
spring:
  application:
    name: eureka-server